---
language: bash
dist: trusty

env:
  - VERSION=9.1-2.1
  - VERSION=9.2-2.1
  - VERSION=9.3-2.1
  - VERSION=9.4-2.1

install:
  - sudo apt-get -qqy update
  - sudo apt-get -qqy install wget
  - sudo wget -qO- https://get.docker.com/ | sh
  - sudo sudo usermod -aG docker "$USER"

before_script:
  - env | sort
  - cd "$VERSION"
  - image="moofish32/postgis-geocoder:$VERSION"

script:
  - docker build --pull -t "$image" .
